// Code generated by oapi-codegen. DO NOT EDIT.
// A second service, on its own host and its own API version. It is a separate
// product so that declining it whole is one decision.

package oks

type Client struct{}

// ListProjects is a real operation of the Kubernetes service.
func (c *Client) ListProjects(ctx context.Context) (*ListProjectsResponse, error) {
	return nil, nil
}

type ListProjectsResponse struct{}
