// Code generated by oapi-codegen. DO NOT EDIT.
// Fixture mimicking the layout Outscale ships: one generated client per
// service, every operation a method on *Client, and three shapes that look like
// operations without being any.

package osc

// Client is the typed client, and the only receiver that carries surface.
type Client struct{}

// ReadVms is a real operation.
func (c *Client) ReadVms(ctx context.Context, body ReadVmsJSONRequestBody) (*ReadVmsResponse, error) {
	return nil, nil
}

// ReadVmsWithBody is the same endpoint taking a raw body. One operation, two
// signatures: counting both doubles the surface.
func (c *Client) ReadVmsWithBody(ctx context.Context, contentType string, body io.Reader) (*ReadVmsResponse, error) {
	return nil, nil
}

// CreateVms is a real operation.
func (c *Client) CreateVms(ctx context.Context, body CreateVmsJSONRequestBody) (*CreateVmsResponse, error) {
	return nil, nil
}

func (c *Client) CreateVmsWithBody(ctx context.Context, contentType string, body io.Reader) (*CreateVmsResponse, error) {
	return nil, nil
}

// ClientRaw carries the same operations at a lower level, with a Raw suffix.
// Counting it would triple the surface.
type ClientRaw struct{}

func (c *ClientRaw) ReadVmsRaw(ctx context.Context, body ReadVmsJSONRequestBody) (*http.Response, error) {
	return nil, nil
}

func (c *ClientRaw) ReadVmsWithBodyRaw(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	return nil, nil
}

// LogRequest exists on ClientRaw alone and is plumbing, not an endpoint.
func (c *ClientRaw) LogRequest() {}

// The response types carry decoding helpers on a value receiver. They are named
// after operations and are not operations.
type ReadVmsResponse struct{}

func (r ReadVmsResponse) StatusCode() int { return 0 }

// An unexported method is not surface either.
func (c *Client) newRequest() {}
